"""Aggiornamento spese

Revision ID: 25a4b9cf4a4e
Revises: 
Create Date: 2025-11-25 10:21:16.921255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25a4b9cf4a4e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spese', sa.Column('tipo_scontrino', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spese', 'tipo_scontrino')
    # ### end Alembic commands ###
