"""Aggiunta colonna citta a prenotazioni

Revision ID: c106ec18dbaa
Revises: 5af04c44d614
Create Date: 2025-11-28 19:46:48.719779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c106ec18dbaa'
down_revision: Union[str, None] = '5af04c44d614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prenotazioni', sa.Column('citta', sa.String(), nullable=True))
    op.alter_column('prenotazioni', 'tipo_mezzo',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('prenotazioni', 'tipo_alloggio',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('hotel', 'bnb', 'ostello', 'appartamento', 'casa_vacanze', 'agriturismo', 'guesthouse', 'altro', name='tipoalloggioenum'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prenotazioni', 'tipo_alloggio',
               existing_type=sa.Enum('hotel', 'bnb', 'ostello', 'appartamento', 'casa_vacanze', 'agriturismo', 'guesthouse', 'altro', name='tipoalloggioenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('prenotazioni', 'tipo_mezzo',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.drop_column('prenotazioni', 'citta')
    # ### end Alembic commands ###
